spring:
    datasource:
        driver-class-name: org.h2.Driver
        username: sa
        password:
        url: "jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                ddl-auto: update
                default_schema: public
                dialect: org.hibernate.dialect.PostgreSQLDialect
                enable_lazy_load_no_trans: true
                format_sql: true
                show_sql: true
                temp:
                    use_jdbc_metadata_defaults: false
                type: trace
                use_sql_comments: false
                generate_statistics: false     
    h2:
        console:
                enabled: true
                path: /h2-dougp_db
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

logging:
    level:
        root: INFO
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

