spring:
    datasource:
        driver-className: org.h2.Driver
        username: sa
        password:
        url: "jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1"

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                generate_statistics: false     
    h2:
        console:
                enabled: true
                path: /h2-dougp_db
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

logging:
    level:
        root: INFO
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

